//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoxiLink {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class VoxityApi : global::System.Configuration.ApplicationSettingsBase {
        
        private static VoxityApi defaultInstance = ((VoxityApi)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VoxityApi())));
        
        public static VoxityApi Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YourRedirectHost")]
        public string HOST {
            get {
                return ((string)(this["HOST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public int PORT {
            get {
                return ((int)(this["PORT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XXXXXXXXXXXXXXXXXXXX")]
        public string CLIENT_ID {
            get {
                return ((string)(this["CLIENT_ID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XXXXXXXXXXXXXXXXXXXX")]
        public string CLIENT_SECRET {
            get {
                return ((string)(this["CLIENT_SECRET"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REFRESH_TOKEN {
            get {
                return ((string)(this["REFRESH_TOKEN"]));
            }
            set {
                this["REFRESH_TOKEN"] = value;
            }
        }
    }
}
